// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TitleSkip","status":true,"description":"","parameters":{}},
{"name":"HIME_QuizSystem","status":true,"description":"v1.0 -","parameters":{"Quiz Root Path":"data/quiz/\r"}},
{"name":"HIME_QuizBattleSystem","status":true,"description":"v1.0 -","parameters":{}},
{"name":"HIME_QuizPointsWindow","status":true,"description":"v1.0 -","parameters":{"Quiz Root Path":"data/quiz/\r"}}
];
